name: IC-workflow

on:
    pull_request:
        branches: [dev]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Update Submodule
              run: |
                  cd Backend-jest-GardenGuru
                  git pull origin dev

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Check Formatting
              run: npm run format:check

            - name: Run Linter
              run: npm run lint

            - name: Install Tests Dependencies
              run: |
                  cd Backend-jest-GardenGuru
                  npm install

            - name: Create .env file
              env:
                MONGO_CONNECT_URL: ${{ secrets.MONGO_CONNECT_URL }}
                DATABASE: ${{ secrets.DATABASE }}
                BASE_URL: ${{ secrets.BASE_URL }}
              run: |
                  cd Backend-jest-GardenGuru
                  touch .env
                  echo BASE_URL=${{ secrets.BASE_URL }} >> .env
              
            - name: Start Server
              run: |
                  touch .env
                  echo MONGO_CONNECT_URL=${{ secrets.MONGO_CONNECT_URL }} >> .env
                  echo DATABASE=${{ secrets.DATABASE }} >> .env 
                  npm run start

            - name: Run Tests
              run: npm test
