name: IC-workflow

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend-API-GardenGuru code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Checkout Backend-jest-GardenGuru code
        uses: actions/checkout@v2
        with:
          repository: owner/Backend-jest-GardenGuru
          ref: dev
          path: Backend-jest-GardenGuru

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Dependencies for Backend-API-GardenGuru
        run: npm install

      - name: Check Formatting
        run: npm run format:check

      - name: Run Linter
        run: npm run lint

      - name: Install Dependencies for Backend-jest-GardenGuru
        run: |
          cd Backend-jest-GardenGuru
          npm install

      - name: Run Tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          MONGO_CONNECT_URL: ${{ secrets.MONGO_CONNECT_URL }}
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          cd Backend-jest-GardenGuru
          touch .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo MONGO_CONNECT_URL=${{ secrets.MONGO_CONNECT_URL }} >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env 
          npm run ic:test
