name: IC-workflow

on:
    pull_request:
        branches: [master, dev]

jobs:
    test:
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Update Submodule
              run: |
                  cd Backend-jest-GardenGuru
                  git pull origin dev

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Check Formatting
              run: npm run format:check

            - name: Run Linter
              run: npm run lint

            - name: Install Tests Dependencies
              run: |
                  cd Backend-jest-GardenGuru
                  npm instal
                  
            - name: Run Tests
              run: npm test
