name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        repository: GardenGuru2324/Backend-API-GardenGuru
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Checkout backend-jest repository
      uses: actions/checkout@v4
      with:
        repository: GardenGuru2324/Backend-jest-GardenGuru
        path: backend-jest

    - name: Install dependencies for backend-jest
      run: npm ci
      working-directory: ./Backend-jest-GardenGuru

    - name: Run tests for backend-jest
      run: npm test
      working-directory: ./Backend-jest-GardenGuru
